angstrom tasks: fix multiline comments
Bitbake used to ignore these but no longer does so, please fix your metadata as errors are likely as a result of this change.
ERROR: There is a comment on line 15 of file /OE/tentacle/sources/meta-angstrom/recipes-angstrom/angstrom/angstrom-gpe-task-game.bb

Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>