angstrom.inc: set dummy default MACHINE_KERNEL_PR to "r0"
machines not using MACHINE_KERNEL_PR would fail for recipes appending letters
(meta-ti) with:

ERROR: Unable to analyse format of PR variable: b#############                                                                                                      | ETA:  00:00:40
ERROR: Error executing a python function in <code>:

The stack trace of python calls that resulted in this exception/failure was:
File: '<code>', lineno: 1, function: <module>
 *** 0001:__anon_629__home_a_mueller_oe_core_sources_openembedded_core_meta_classes_base_bbclass(d)
     0002:__anon_975__home_a_mueller_oe_core_sources_openembedded_core_meta_classes_insane_bbclass(d)
     0003:__anon_235__home_a_mueller_oe_core_sources_openembedded_core_meta_classes_package_bbclass(d)
     0004:__anon_20__home_a_mueller_oe_core_sources_openembedded_core_meta_classes_debian_bbclass(d)
     0005:__anon_45__home_a_mueller_oe_core_sources_openembedded_core_meta_classes_blacklist_bbclass(d)
File: '__anon_629__home_a_mueller_oe_core_sources_openembedded_core_meta_classes_base_bbclass', lineno: 80, function: __anon_629__home_a_mueller_oe_core_sources_openembedded_core_meta_classes_base_bbclass
     0076:        pr_prefix = re.search("\D+",pr)
     0077:        prval = re.search("\d+",pr)
     0078:        if pr_prefix is None or prval is None:
     0079:            bb.error("Unable to analyse format of PR variable: %s" % pr)
 *** 0080:        nval = int(prval.group(0)) + int(princ)
     0081:        pr = pr_prefix.group(0) + str(nval) + pr[prval.end():]
     0082:        d.setVar('PR', pr)
     0083:
     0084:    pn = d.getVar('PN', True)
Exception: AttributeError: 'NoneType' object has no attribute 'group'

ERROR: Failed to parse recipe: /home/a.mueller/oe-core/sources/meta-ti/recipes-bsp/powervr-drivers/omap3-sgx-modules_4.05.00.03.bb

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>
Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>