images: successor of task-xserver is packagegroup-core-x11-xserver
error message is something like:

ERROR: Required build target 'xfce-nm-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['xfce-nm-image', 'packagegroup-xserver']

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>
Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>