angstrom: Override OE-Core for virtual/libgl PREFERRED_PROVIDER
Weaker define means OE-Core definition takes over and it results
in conflicts

ERROR: Multiple .bb files are due to be built which each provide
virtual/libgl
(/home/kraj/work/angstrom/sources/openembedded-core/meta/recipes-graphics/mesa/mesa-gl_9.1.6.bb
/home/kraj/work/angstrom/sources/openembedded-core/meta/recipes-graphics/mesa/mesa_9.1.6.bb).
 This usually means one provides something the other doesn't and should.

Signed-off-by: Khem Raj <raj.khem@gmail.com>