vim: overlay from meta-oe to work around hg fetcher
The hg fetcher can't handle snapshots:

NOTE: recipe vim-7.4.481-r0: task do_fetch: Started
ERROR: No checksum specified for
/build/jenkins/angstrom-v2015.06-shared/downloads/vim_vim.googlecode.com_.hg._v7-4-481.tar.gz,
please add at least one to the recipe:
SRC_URI[md5sum] = "56358f031ee7d4f782d212a8d23af97e"
SRC_URI[sha256sum] =
"9c29ce05c67d697716f0ac5ab537d5762a0161cb0213d4bf48a92ad7295b2a1a"
ERROR: Function failed: Fetcher failure for URL:
'http://sources.angstrom-distribution.org/v2015.06/vim_vim.googlecode.com_.hg._v7-4-481.tar.gz;protocol=https;module=vim'.
Missing SRC_URI checksum

Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>